[project]
name = "taccoform-localstack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awscli-local>=0.22.2",
    "terraform-local>=0.25.0",
]
